source "https://rubygems.org"

gem "test-kitchen"
gem "kitchen-vagrant"
gem "kitchen-ec2"
gem "kitchen-digitalocean"
gem "kitchen-inspec"
gem "kitchen-ansible"
gem "kitchen-docker"
gem "kitchen-sync"
gem "kitchen-ssh"
gem "inspec"
gem "berkshelf"
