#!/usr/bin/env bash

function main {
  if [[ -z "${1:-}" ]]; then
    return 0
  fi

  local nm_host="$1"; shift

  if [[ ! -f ".kitchen/${nm_host}.yml" ]]; then
    return 0
  fi

  cat ".kitchen/${nm_host}.yml" \
    | ruby -rjson -ryaml -e 'puts YAML.load(STDIN.read()).to_json' \
    | jq -r --arg host "${nm_host}" \
       '"Host \($host)\n\tHostname \(.hostname//"null")\n\tPort \(.port//22)\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n\tIdentityFile \(.ssh_key)\n\n"'
}

source sub "$0" "$@"
