#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  rbenv install -s
  gem install bundler --conservative -v "${BUNDLER_VERSION}"

  bundle config build.nokogiri --use-system-libraries --with-xml2-config="$(which xml2-config)" --with-xslt-config="$(which xslt-config)"
  block compile bundler

  mkdir -p "$shome/bin"
  cd "$shome/bin"
  (set +f; ln -nfs \
    ../vendor/bundle/bin/kitchen \
    ../vendor/bundle/bin/berks \
    "$shome/bin/")
}

main "$@"
